### ISSUE TITLE
Long compile times of the verilated model 

### ISSUE THREAD

**Issue by suehtamacv** [pulp-platform/mempool#4]
MemPool takes a long time to Verilate. The 256-core version of MemPool takes about 6h to compile, making its inclusion on the CI completely unfeasible. 

A solution similar to pulp-platform/ara#51 might be applicable here. It requires compiling Verilator with clang---which on the version linked in this repository currently breaks---but solving this would allow us to test the large MemPool configuration on the CI. 

What do you think, @SamuelRiedel?

**Comment by SamuelRiedel** [comment]
I love it.
